#
# Application name and list of source files.
#

NAME=osview
CCSRCS=$(NAME).cpp npy.cpp



#
# Dependency libraries
#

PKG_LIBS=-lRGBD -lR3Surfels -lR3Graphics -lR3Shapes -lR2Shapes -lRNNets -lRNMath -lRNBasics -ljpeg -lpng


#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


