DATA:
  data_root: /data/openscene_datasets/replica_3d
  data_root_2d_fused_feature: /data/openscene_datasets/multiview_openseg
  feature_2d_extractor: openseg
  voxel_size: 0.02
  input_color: False
  use_shm: False


TEST:
  split:   # split in [train, val and test]
  prompt_eng: True
  labelset: matterport
  mark_no_feature_to_unknown: True
  feature_type: 'ensemble' # 'distill' | 'fusion' | 'ensemble'
  save_feature_as_numpy: True
  vis_pred: True
  vis_input: True
  vis_gt: True
  test_workers: 8
  test_gpu: [0]
  test_batch_size: 1
  test_repeats: 1
  model_path: 'https://cvg-data.inf.ethz.ch/openscene/models/matterport_openseg.pth.tar'
  save_folder:
  arch_3d: MinkUNet18A
  evaluate: True
  manual_seed: 3407
  eval_iou: False

Distributed:
  dist_url: tcp://127.0.0.1:6787
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0