dataset_root: null
dataset_config: null
scene_id: null
start: 0
end: -1
stride: 50
desired_height: 480
desired_width: 640
box_threshold: 0.2
text_threshold: 0.2
nms_threshold: 0.5
class_set: null
classes_file: /home/kuwajerw/repos/new_conceptgraphs/concept-graphs/conceptgraph/scannet200_classes.txt
add_bg_classes: false
accumu_classes: false
sam_variant: sam
save_video: false
device: cuda
use_slow_vis: false
exp_suffix: _exp_label