version: "3"

services:
  concept_graphs:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: open_semantic/concept_graphs:latest
    restart: unless-stopped
    network_mode: host
    ipc: host
    environment:
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - DISPLAY=$DISPLAY
      - VGL_DISPLAY=${RENDER_DISPLAY:-":1"}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - $DATA_DIR/:/mnt/
      - ./:/opt/src
    runtime: nvidia
    privileged: true
    command: bash